name: 'Deploy Backend'

# Controls when the workflow will run
on:
  # This only happens manually for now
  workflow_dispatch

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/641228848625/locations/global/workloadIdentityPools/github-action-pool/providers/github-token-provider'
          service_account: 'github-action-runner@refined-asset-359508.iam.gserviceaccount.com'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'ott-backend'
          #image: 'gcr.io/cloudrun/hello'
          region: 'europe-west4'
          source: 'api'

